# Generated by Django 6.0.4 on 2026-04-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='cuise',
        ),
    ]
